version: 2.1

aliases:
  - &checkout
    checkout

main_flow_config: &main_flow_config
  working_directory: ~/favware
  docker:
    - image: circleci/node:10-browsers

build_and_deploy_config: &build_and_deploy_config
  working_directory: ~/favware
  docker:
    - image: circleci/node:8

run_yarn: &run_yarn
  name: Install yarn packages
  command: yarn install --frozen-lockfile --ignore-engines

save_yarn: &save_yarn
  save_cache:
    name: Save Yarn Package Cache
    key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
      - node_modules

save_dist: &save_dist
  save_cache:
    name: Save dist folder
    key: dist-latest
    paths:
      - dist

restore_yarn: &restore_yarn
  restore_cache:
    name: Restore Yarn Package Cache
    key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}

restore_dist: &restore_dist
  restore_cache:
    name: Restore dist folder
    key: dist-latest

commands:
  linting:
    steps:
    - *checkout
    - <<: *restore_yarn
    - run:
        <<: *run_yarn
    - run:
        name: Run Linting
        command: yarn lint
    - <<: *save_yarn
  testing:
    steps:
    - *checkout
    - <<: *restore_yarn
    - run:
        <<: *run_yarn
    - run:
        name: Run Tests
        command: yarn test --no-watch
  building:
    steps:
    - *checkout
    - <<: *restore_yarn
    - run:
        <<: *run_yarn
    - run:
        name: Build Firebase
        command: pushd functions && yarn --ignore-engines && popd
    - run:
        name: Building
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn build:ssr
          else
              yarn build
          fi
    - <<: *save_dist
  deployment:
    steps:
    - *checkout
    - <<: *restore_yarn
    - <<: *restore_dist
    - run:
        name: Build Firebase
        command: pushd functions && yarn --ignore-engines && popd
    - run:
        name: Install Firebase Tools
        command: yarn add firebase-tools --ignore-engines
    - run:
        name: Deploy Firebase
        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

jobs:
  test:
    <<: *main_flow_config
    steps:
      - testing
  lint:
    <<: *main_flow_config
    steps:
      - linting
  build:
    <<: *build_and_deploy_config
    steps:
      - building
  deploy:
    <<: *build_and_deploy_config
    steps:
      - deployment

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - test
      - lint
      - build:
          requires:
            - lint
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
