version: 2

# Machine configuration
machine:
  node:
    version: 11
  npm:
    version: 6

# List of jobs
jobs:

  # Bundle Testing
  test:
    working_directory: ~/favware-website
    docker:
      - image: circleci/node:11-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --ignore-engines
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: Linting
          command: yarn lint
      - run:
          name: Testing
          command: yarn test --no-watch

  # Firebase Build
  build:
    working_directory: ~/favware
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --ignore-engines
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: Build Firebase
          command: pushd functions && yarn --ignore-engines && popd
      - run:
          name: Building
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                yarn build:ssr
            else
                yarn build
            fi
      # Cache the dist folder for the deploy job
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  # Firebase Deploy
  deploy:
    working_directory: ~/favware
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build Firebase
          command: pushd functions && yarn --ignore-engines && popd
      - run:
          name: Install Firebase Tools
          command: yarn add firebase-tools --ignore-engines
      - run:
          name: Deploy Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master