name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn
      - name: Build Bundle
        run: yarn build
      # - name: Deploy to Firebase
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      #   run: ./node_modules/.bin/firebase deploy --token=${{ secrets.FIREBASE_TOKEN }}
