name: Code Quality

on: [push, pull_request]

jobs:
  TSLint:
    name: TSLint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-yarn-${{ env.cache-name }}-
          ${{ runner.OS }}-yarn-
          ${{ runner.OS }}-

    - name: Install Deps
      run: yarn
    - name: Run TSLint
      run: yarn lint

  Test:
    name: Jasmine Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          ${{ runner.OS }}-yarn-${{ env.cache-name }}-
          ${{ runner.OS }}-yarn-
          ${{ runner.OS }}-

    - name: Install Deps
      run: yarn
    - name: Test
      run: yarn test
