name: Continuous Integration

on:
  pull_request:
  push:
    branches-ignore:
      - master
      - main
      - angular-legacy

jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Restore CI Cache
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
      - name: Install Deps
        run: yarn
      - name: Run ESLint
        run: yarn lint --fix=false

  Build:
    name: Compiling NextJS
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Restore CI Cache
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
      - name: Install NodeJS Dependencies
        run: yarn
      - name: Build NextJS
        run: yarn build
